jobName: flink_basic_streaming
jobConsumerGroupName: flink_basic_streaming_cg_v1
kafkaSourceBrokers: localhost:9092
kafkaSinkBrokers: localhost:9092
startingOffset: earliest
restartCount: 10
restartDelay: 10
stream1:
  source: input1
  sink: output1
  sourceParallelism: 2
  mapParallelism: 2
  sinkParallelism: 2

checkpointConfig:
  enabled: true
  checkpointInterval: 30000
  pauseBtwCheckpoints: 30000
  checkpointTimeout: 300000
  maxConcurrentCheckpoints: 1
  preferCheckpointForRecovery: true
  checkpointMode: exactly_once
  checkpointDataUri: file:///Users/mathewpallan/flinkstate
